language: python
python:
    - "3.6"
    - "3.7"
before_install:
    - conda env create -f environment.yml
    - conda activate podo
install:
    - pip install -e .
script:
    - py.test --cov .
after_success:
  coveralls

