language: python
python:
    - "3.6"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
    - sudo apt-get update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - echo ". /home/travis/miniconda/etc/profile.d/conda.sh" >> ~/.bashrc
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    # Set up conda environment for testing
    - conda env create -f environment.yml
    - conda activate podo
    - pip install -e .
script:
    - py.test --cov .
after_success:
  coveralls
