name: podo
channels:
- defaults
- conda-forge
dependencies:
- python=3
- pytest
- pytest-cov
- coverage
- coveralls
- flake8
- pyinstaller
- numpy
- pandas
- jpype1
- pims
- scikit-image
- wxpython
- pip:
  - gooey
