name: podo
channels:
- conda-forge
dependencies:
- python=3.6
- python.app
- numpy
- pandas
- cython
- matplotlib
- pyinstaller
- pip:
  - javabridge
  - python-bioformats
  - git+https://github.com/scikit-image/scikit-image
  - git+https://github.com/chriskiehl/Gooey
