name: podo
channels:
- conda-forge
dependencies:
- python=3.6
- python.app
- numpy
- pims
- jpype1
- pillow
- imageio
- tifffile
- matplotlib
- pyinstaller
- cython
- pip:
  - git+https://github.com/scikit-image/scikit-image
  - git+https://github.com/chriskiehl/Gooey
