name: podo
channels:
- defaults
- conda-forge
dependencies:
- python=3
- pytest
- pytest-cov
- coverage
- coveralls
- flake8
- pyinstaller
- jpype1
- tifffile
- numpy
- pandas
- scikit-image
- wxpython
- pip:
  - gooey
  - git+https://github.com/soft-matter/pims
